<a href="https://colab.research.google.com/github/jkworldchampion/Military_CodingStudy/blob/main/deeplearning/computer_vision_tf2_ch1_ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# NoteBook 0 : 첫 환경설정하기

In [2]:
cd /content/drive/MyDrive/Colab_Notebooks/Machine_learning/book/computer_vision_tf2

/content/drive/MyDrive/Colab_Notebooks/Machine_learning/book/computer_vision_tf2


In [6]:
!git clone "https://github.com/wikibook/dl-vision.git"  # git clone을 통해 Drive안에 파일들 불러오기

Cloning into 'dl-vision'...
remote: Enumerating objects: 336, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 336 (delta 37), reused 72 (delta 33), pack-reused 258
Receiving objects: 100% (336/336), 45.67 MiB | 14.03 MiB/s, done.
Resolving deltas: 100% (63/63), done.
Checking out files: 100% (208/208), done.


In [3]:
# 가볍게 계산해보기
import tensorflow as tf

x1 = tf.constant([[0, 1], [2, 3]])
x2 = tf.constant(10)
x = x1*x2
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [20, 30]], dtype=int32)>

# NoteBook 1 : 신경망을 처음부터 구성하고 훈련시키기

In [15]:
# 이부분은 basic_deeplearning에서 지겹도록 했으니 넘어간다.

# Notebook 2 : 케라스로 구현한 MNIST문제

In [4]:
import tensorflow as tf

### *잠시 확인하는 eager execution(조급한 실행)과 lazy execution(느긋한 실행)

In [14]:
a = tf.constant([1, 2, 3])
b = tf.constant([0, 0, 1])
c = tf.add(a, b)
print(c)  # tensorflow2에서는 조급한 실행이 default이기 때문에 바로 결과값이 나온다.

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [17]:
@tf.function
def compute(a, b, c):
    d = a * b + c 
    e = a * b * c
    return d, e

위와같은 경우 a * b가 두번 연산될 수 있지만, 텐서플로에서 제공하는 오토그래프 @tf.function을 사용하면 자동으로 최적화를 해준다.

## Input data

In [19]:
num_classes = 10
img_rows, img_cols = 28, 28
num_channels = 1
input_shape = (img_rows, img_cols, num_channels)

(x_train, y_train),(x_test, y_test) = tf.keras.datasets.mnist.load_data()  # 데이터 불러오기
x_train, x_test = x_train / 255.0, x_test / 255.0   # 데이터를 0~1사이값으로 변환

## Buliding a simple model

In [20]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [21]:
model.summary()

ValueError: ignored

## Launch training

In [7]:
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
callbacks = [tf.keras.callbacks.TensorBoard('./keras')]
model.fit(x_train, y_train, epochs=25, verbose=1, validation_data=(x_test, y_test), callbacks=callbacks)

Epoch 1/25
1875/1875 [==============================] - 8s 3ms/step - loss: 0.6408 - accuracy: 0.8375 - val_loss: 0.3530 - val_accuracy: 0.9044
Epoch 2/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3350 - accuracy: 0.9073 - val_loss: 0.2894 - val_accuracy: 0.9189
Epoch 3/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2872 - accuracy: 0.9197 - val_loss: 0.2642 - val_accuracy: 0.9255
Epoch 4/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2572 - accuracy: 0.9282 - val_loss: 0.2377 - val_accuracy: 0.9332
Epoch 5/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2341 - accuracy: 0.9345 - val_loss: 0.2168 - val_accuracy: 0.9391
Epoch 6/25
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2153 - accuracy: 0.9401 - val_loss: 0.2027 - val_accuracy: 0.9425
Epoch 7/25
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1994 - accuracy: 0.9440 - val_loss: 0.1902 - val_accuracy:

In [8]:
estimator = tf.keras.estimator.model_to_estimator(model, model_dir='./estimator_dir')

INFO:tensorflow:Using default config.
INFO:tensorflow:Using the Keras model provided.


/usr/local/lib/python3.7/dist-packages/keras/backend.py:450: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


INFO:tensorflow:Using config: {'_model_dir': './estimator_dir', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [10]:
BATCH_SIZE = 32
def train_input_fn():
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    train_dataset = train_dataset.batch(BATCH_SIZE).repeat()
    return train_dataset

estimator.train(train_input_fn, steps=len(x_train)//BATCH_SIZE)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
INFO:tensorflow:Calling model_fn.


/usr/local/lib/python3.7/dist-packages/keras/backend.py:450: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Warm-starting with WarmStartSettings: WarmStartSettings(ckpt_to_initialize_from='./estimator_dir/keras/keras_model.ckpt', vars_to_warm_start='.*', var_name_to_vocab_info={}, var_name_to_prev_var_name={})
INFO:tensorflow:Warm-starting from: ./estimator_dir/keras/keras_model.ckpt
INFO:tensorflow:Warm-starting variables only in TRAINABLE_VARIABLES.
INFO:tensorflow:Warm-started 4 variables.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into ./estimator_dir/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.048092213, step = 0
INFO:tensorflow:global_step/sec: 497.464
INFO:tensorflow:loss = 0.11297741, step = 100 (0.204 sec)
INFO:tensorflow:global_s

## TensorBoard

In [22]:
model.compile(optimizer='sgd',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
callbacks = [tf.keras.callbacks.TensorBoard('./logs_keras')]
model.fit(x_train, y_train, epochs=5, verbose=1, validation_data = (x_test, y_test), callbacks=callbacks)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.6371 - accuracy: 0.8403 - val_loss: 0.3546 - val_accuracy: 0.9057
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3350 - accuracy: 0.9061 - val_loss: 0.2923 - val_accuracy: 0.9172
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2863 - accuracy: 0.9193 - val_loss: 0.2583 - val_accuracy: 0.9254
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2557 - accuracy: 0.9273 - val_loss: 0.2356 - val_accuracy: 0.9311
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2331 - accuracy: 0.9345 - val_loss: 0.2173 - val_accuracy: 0.9384


In [25]:
! tensorboard --logdir ./logs_keras


NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.8.0 at http://localhost:6006/ (Press CTRL+C to quit)
^C
